# Generated by Django 3.2.4 on 2022-01-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnpps', '0012_auto_20220130_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_id1',
        ),
        migrations.AlterField(
            model_name='order',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='gnpps.clien'),
        ),
    ]
