# Generated by Django 3.2.4 on 2022-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnpps', '0014_remove_distribution_client_id1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=20)),
                ('purchase_date', models.DateField()),
                ('quantity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('thickness', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('quantity', models.CharField(max_length=20)),
            ],
        ),
    ]
